config/routes.rb
require 'sidekiq/web'

ForeverFamilyFoundation::Application.routes.draw do
  ActiveAdmin.routes(self)
  mount Sidekiq::Web, at: '/sidekiq'

  root to: 'site#index'
  # Need this for legacy links hard-coded into Love Knows No Death PDF
  get 'site/page/:id', to: 'site#page'
  # get '/pages/signs-of-life-magazine', to redirect('/', status: 301)
  

  devise_for :users, controllers: {
    registrations: 'registrations',
    invitations: 'invitations',
    sessions: 'sessions'
  }

  devise_scope :user do
    authenticated :user do
      root to: 'users#show', as: :user_profile
    end
  end

  resources :users, only: :show
  resources :pages, only: [:show], controller: :cms_pages
  resources :user_preference_selections, only: [:edit, :update]
  resources :events, only: [:index, :show]

  match '/404', to: 'exceptions#not_found', via: :all
  match '/500', to: 'exceptions#internal_error', via: :all
  match '/422', to: 'exceptions#unacceptable', via: :all

  resources :sitterforms
  resources :mediumforms
  resource :adg_registration

  # billing routes - not in use
  # mount StripeEvent::Engine, at: '/webhooks/stripe'
  # resources :businesses
  # resources :family_member_invitations, only: [:create, :new]
  # resources :family_members, only: [:destroy]
  # resource :pricing, controller: :pricing
  # resource :subscription do
  #   patch :resume
  # end
  # resources :payments
  # resources :charges
  # resource :card
end

app/controllers/adg_registrations_controller.rb
class AdgRegistrationsController < ApplicationController
  before_action :require_registration

  def new
    AdgQuestion.all.each do |adg_question|
      current_user.adg_answers.build adg_question_id: adg_question.id
    end
  end

  def edit; end

  def update
    current_user.adg_answers_attributes = adg_registration_params['adg_answers_attributes'].values
    if current_user.valid?
      current_user.save
      redirect_to current_user, notice: t('.success')
    else
      flash[:error] = current_user.errors.full_messages.join(' ')
      render 'edit'
    end
  end


  private

  def adg_registration_params
    params.require(:user).permit adg_answers_attributes: [:adg_question_id, :answer, :id]
  end

  def require_registration
    unless current_user
      redirect_to new_user_registration_path, notice: I18n.t('adg_registrations.redirect')
    end
  end
end

app/views/adg_registrations/_form.html.haml
= simple_form_for current_user, url: adg_registration_path do |f|
  = f.simple_fields_for :adg_answers do |adg|
    = adg.input :adg_question_id, as: :hidden
    - if adg.object.adg_question.show_radio
      = adg.input :answer, as: :radio_buttons, label: adg.object.adg_question.question
    - else
      = adg.input :answer, as: :text, label: adg.object.adg_question.question
  = f.submit 'Save Registration', class: 'btn btn-primary'

app/views/adg_registrations/edit.html.haml
= render 'form'

app/views/adg_registrations/new.html.haml
= form_tag adg_registration_path do
  %table.adg_questions
    - @adg_questions.each do |adg_question|
      - adg_answer = current_user.adg_answers.find_by_adg_question_id(adg_question)
      %tr
        %td
          = adg_question.question
        %td    
          - if adg_question.show_radio
            %label{ for: "adg_registration_radio_val[#{adg_question.id}]_yes", class: :radio } Yes
            = radio_button "adg_registration", "radio_val[#{adg_question.id}]", "yes", :checked => (adg_answer.present? and adg_answer.radio_val == "yes"), class: :yes
            /
            %label{ for: "adg_registration_radio_val[#{adg_question.id}]_no", class: :radio } No
            = radio_button "adg_registration", "radio_val[#{adg_question.id}]", "no", :checked => (adg_answer.present? and adg_answer.radio_val == "no"), class: :no


          %div.answer_field{style: "display: #{(adg_question.show_radio && adg_answer.try(:answer).blank?) ? 'none' : 'block'}"}
            = text_area_tag "adg_registration[answer[#{adg_question.id}]]", adg_answer.try(:answer), class: :simple



  - user_adg_preferences = current_user.adg_preferences.all
  - Preference.adg_preferences.each do |adg_preference|
    = check_box_tag "adg_registration[adg_preference_ids][]", adg_preference.id, user_adg_preferences.include?(adg_preference)
    = adg_preference.name
    %br
    %br
  = render :partial => 'shared/form_submit', :locals => { :text => t('submit') }